using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Player : MonoBehaviour
{
    public float forceMultiplier = 3f;
    public float maximumVelocity = 3f;

    private Rigidbody rb;

    // Start is called before the first frame update
    void Start()
    {
        
        rb = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        var horizontalInput = Input.GetAxis("Horizontal");

        if  (rb.velocity.magnitude <= 5f)
        {
          rb.AddForce(new Vector3(horizontalInput * 3f, 0 , 0));
        }
    }
    
        private void OnCollisionEnter(Collision collision)
        {
            if (collision.gameObject.CompareTag("Hazard"))
            {
                //GameManager.gameOver();
            // Destroy(gameObject);
            
            }
        }
}
